// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA53uysiPOkNBiHBGplxfla1lpD1h9OegI',
    appId: '1:297661181831:web:aabd2b0ca063a4ea5c6d22',
    messagingSenderId: '297661181831',
    projectId: 'capteurappsofip59',
    authDomain: 'capteurappsofip59.firebaseapp.com',
    storageBucket: 'capteurappsofip59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXuPfaxNmmJowLNrXADBoYv5wUuqZT3cY',
    appId: '1:297661181831:android:3dc6aa347d1ee72a5c6d22',
    messagingSenderId: '297661181831',
    projectId: 'capteurappsofip59',
    storageBucket: 'capteurappsofip59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzfv3FITnOPu5GzIGakZ8-oVtYzYXCl6I',
    appId: '1:297661181831:ios:f320541f9992e3335c6d22',
    messagingSenderId: '297661181831',
    projectId: 'capteurappsofip59',
    storageBucket: 'capteurappsofip59.appspot.com',
    iosBundleId: 'com.example.capteurapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzfv3FITnOPu5GzIGakZ8-oVtYzYXCl6I',
    appId: '1:297661181831:ios:65747b16c05184ba5c6d22',
    messagingSenderId: '297661181831',
    projectId: 'capteurappsofip59',
    storageBucket: 'capteurappsofip59.appspot.com',
    iosBundleId: 'com.example.capteurapp.RunnerTests',
  );
}
